### ISSUE TITLE
The regulator overheats

### ISSUE THREAD

**Issue by brandonbrown2** [OpenMYR/ESP12E.6#1]
The linear regulator runs hot due to burning too much power when the ESP8266 is functioning at the higher end of its current usage requirements. This causes the device to reset. This has only been demonstrated when the device is running in softAP broadcast mode, and can be triggered by having more than one client connect to the station. It may take multiple connects and disconnects to trigger it, but it does happen. This does not happen with the servo board because the motor voltage rails of that design are only 5 volts, meaning that only 1.6 volts are burned, as opposed to the 8.6 volts burned with the stepper design.

**Comment by Vzor-** [comment]
Confirmed with both of the boards here.

**Comment by chradams** [comment]
We will be addressing this issue with a switching regulator for 12VDC powered boards. The regulator has been tested on its own PCB and added to IO-Changes @ 3e671ce91a2bfdb306f3759afbd26d7521569aa6. Issue will be closed once [IO-Changes](https://github.com/OpenMYR/ESP12E.6/tree/IO-Changes) 3e671ce91a2bfdb306f3759afbd26d7521569aa6 is tested.

**Comment by Vzor-** [comment]
fixed as of 3e671ce91a2bfdb306f3759afbd26d7521569aa6
